/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'midnight-ink': '#111827',
        'ghost-gray': '#3f4654',
        'mist-gray': '#6b7589',
        'canvas-white': '#ffffff',
        'pale-cloud': '#f1f5f9',
        'mint-glaze': '#d6fcf4',
        'lavender-mist': '#d8e0ea',
        'royal-amethyst': '#862fe7',
        'soft-amethyst': '#ad6df4',
        'muted-amethyst': '#bd8ff0',
        'deep-plum': '#5f259e',
        'fuchsia-glow': '#ff5fe4',
        'rose-bloom': '#e22ba4',
        'sunset-orange': '#dc5f05',
      },
      fontFamily: {
        bricolagegrotesque: ['"Bricolage Grotesque"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        inter: ['"Inter"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'caption': ['12px', { lineHeight: '1.6', letterSpacing: '1.2px' }],
        'body-sm': ['14px', { lineHeight: '1.5', letterSpacing: '1.4px' }],
        'body': ['16px', { lineHeight: '1.5', letterSpacing: '1.6px' }],
        'body-lg': ['18px', { lineHeight: '1.33', letterSpacing: '1.8px' }],
        'subheading': ['20px', { lineHeight: '1.25', letterSpacing: '-0.5px' }],
        'heading-sm': ['22px', { lineHeight: '1.2', letterSpacing: '-0.55px' }],
        'heading': ['24px', { lineHeight: '1.2', letterSpacing: '-0.6px' }],
        'heading-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.8px' }],
        'display-sm': ['48px', { lineHeight: '1', letterSpacing: '-1.2px' }],
        'display': ['56px', { lineHeight: '1', letterSpacing: '-1.4px' }],
      },
      spacing: {
        '4': '4px',
        '8': '8px',
        '12': '12px',
        '16': '16px',
        '20': '20px',
        '24': '24px',
        '32': '32px',
        '40': '40px',
        '48': '48px',
        '64': '64px',
        '80': '80px',
        '96': '96px',
        '112': '112px',
        '128': '128px',
        '240': '240px',
      },
      borderRadius: {
        'lg': '8px',
        'xl': '12px',
        '2xl': '16px',
        '3xl': '24px',
        'full': '9999px',
        'cards': '24px',
        'badges': '9999px',
        'images': '16px',
        'inputs': '12px',
        'avatars': '9999px',
        'buttons': '12px',
        'navitems': '8px',
      },
      boxShadow: {
        'subtle': 'rgba(11, 61, 121, 0.16) 0px 0px 0px 1px inset',
      }
    },
  },
  plugins: [],
}
